import { AppProps } from 'next/dist/shared/lib/router/router';
import Head from 'next/head';
import Router from 'next/router';
import '../styles/globals.css';
import ym from 'react-yandex-metrika';
import { YMInitializer } from 'react-yandex-metrika';

function MyApp({ Component, pageProps, router }: AppProps): JSX.Element {
  Router.events.on('routeChangeComplete', (url: string) => {
    if (typeof window !== undefined) {
      ym('hit', url);
    }
  });
  return (
    <>
      <Head>
        <title>TopApp</title>
        <meta name='description' content='Generated by create next app' />
        <meta property='og:url' content={process.env.NEXT_PUBLIC_DOMAIN + router.asPath} />
        <meta property='og:locale' content='ru_RU' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://mc.yandex.ru' />
      </Head>
      <YMInitializer accounts={[]} options={{ webvisor: true, defer: true }} version='2' />
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
